name: GCP AMI manual publish

on:
  workflow_dispatch:

jobs:
  build:
    name: Build the GCP AMIs using Packer
    strategy:
      matrix:
        image_family: [ubuntu-2004-lts, ubuntu-2004-lts-arm64]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      PKR_VAR_project_id: spacelift-workers
      PKR_VAR_account_file: ./gcp.json
      PKR_VAR_image_base_name: spacelift-worker
      PKR_VAR_image_family: spacelift-worker
      PKR_VAR_source_image_family: ${{ matrix.image_family }}

    steps:
      - name: Check out the source code
        uses: actions/checkout@main

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-duration-seconds: 3600

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Create account file for GCP
        run: |
          echo '${{ secrets.GCP_CREDENTIALS_JSON }}' > ${{ env.PKR_VAR_account_file }}

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - name: Export suffix for GCP
        run: |
          echo "PKR_VAR_suffix=$(date +%s)-$(cat /dev/urandom | tr -dc 'a-z0-9' | head -c 8)" >> $GITHUB_ENV

      - name: Validate the Packer template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          target: gcp.pkr.hcl
      
      - name: GCP => Build the AMI using Packer for US
        uses: hashicorp/packer-github-actions@master
        env:
          PKR_VAR_image_storage_location: us
          PKR_VAR_zone: us-central1-a
        with:
          command: build
          target: gcp.pkr.hcl

      - name: GCP => Build the AMI using Packer for EU
        uses: hashicorp/packer-github-actions@master
        env:
          PKR_VAR_image_storage_location: eu
          PKR_VAR_zone: europe-west1-d
        with:
          command: build
          target: gcp.pkr.hcl

      - name: GCP => Build the AMI using Packer for Asia
        uses: hashicorp/packer-github-actions@master
        env:
          PKR_VAR_image_storage_location: asia
          PKR_VAR_zone: asia-northeast2-a
        with:
          command: build
          target: gcp.pkr.hcl

      - rame: Set env var for base image name
        run: |
          echo ARCHITECTURE=${{ matrix.image_family == 'ubuntu-2004-lts-arm64' && 'arm64' || 'x64' }} >> $GITHUB_ENV

      - name: GCP => Add IAM policy binding to the Compute Engine images
        run: |
          gcloud compute images add-iam-policy-binding ${PKR_VAR_image_base_name}-us-${PKR_VAR_suffix}-${ARCHITECTURE} --member='allAuthenticatedUsers' --role='roles/compute.imageUser'
          gcloud compute images add-iam-policy-binding ${PKR_VAR_image_base_name}-eu-${PKR_VAR_suffix}-${ARCHITECTURE} --member='allAuthenticatedUsers' --role='roles/compute.imageUser'
          gcloud compute images add-iam-policy-binding ${PKR_VAR_image_base_name}-asia-${PKR_VAR_suffix}-${ARCHITECTURE} --member='allAuthenticatedUsers' --role='roles/compute.imageUser'
